version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Standard linters (enabled by default):
  # errcheck, gosimple, govet, ineffassign, staticcheck, unused
  enable:
    - bodyclose
    - gocritic
    - gosec
    - misspell
    - revive
    - unparam

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    misspell:
      locale: US
    revive:
      # revive is a successor of golint
      rules:
        - name: exported
          severity: warning
        - name: package-comments
          severity: warning

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
      - linters:
          - staticcheck
        text: "SA9003:" # Ignore empty branch warnings (can be used for placeholders)

issues:
  # Show all issues
  max-issues-per-linter: 0
  max-same-issues: 0
